### PR TITLE
relocate call_notifiers(MACHINE_NOTIFY_EXIT) for smooth shutdown

### PR DESCRIPTION
**Pull request by markwkidd**
This PR addresses https://github.com/libretro/mame2010-libretro/issues/95

Thanks @r-type for your help on this.

### CODE REVIEW

**Comment by retro-wertz** [comment]
source files are in C, although it does work why change it to C++ comments?

**Comment by markwkidd** [comment]
Thank you for taking a look at this PR!. mame2010 uses lots of C++ style comments -- it mixes together both formats :) However I just switched some of my comments from C++ to C-style in `machine.c` because they might as well be C-style

On the other hand there are a few existing comments in `ui.c` that I changed from C to C++ style but that is because I wanted to comment out a whole block and the C-style comments were making it hard to do that.

**Comment by twinaphex** [comment]
Let's just try to change those comments to C-style instead. 

If you can do that, I can merge this PR.

**Comment by markwkidd** [comment]
Fair enough @twinaphex.

I just pushed commits so there should be no trace of C++ comments in either of these files. Hopefully that makes the PR ready to go, but let me know if there are other changes to make :)

**Comment by twinaphex** [comment]
Ok, merging this then. Thanks.

**Pull request merged**
