### PR TITLE
Add core option for display aspect ratio and fix refresh rate value

### PR DESCRIPTION
**Pull request by wonder199999**

### CODE REVIEW

**Comment by dankcushions** [comment]
I'm confused - shouldn't cores always provide the correct aspect ratio? this can be overridden through retroarch aspect ratio options if needed

**Comment by wonder199999** [comment]
hi dankcushions .
Mame2010 itself also provides "par" and fixed "standard" mode ,  probably because some games in "par" mode , the screen ratio is strange and distorted . such as CPS1/2 (384 * 224 , 12:7).
In fact , lr-fbalpha has a similar approach , and aspect ratio can have the choice "PAR" and "DAR" . 
viostorm

**Comment by dankcushions** [comment]
Thanks - then I think this option should be name PAR/DAR, to be consistent with FBA - the current options don't really mean anything. Also DAR should be the default.

**Comment by wonder199999** [comment]
I think you're right ，thanks for your advice.

**Pull request closed without merging**
