### PR TITLE
refactor and libretro-ize mame paths and file loading

### PR DESCRIPTION
**Pull request by markwkidd**
Using the folder structure of mame2003 as a template, this PR organizes MAME's various folders (samples, artwork, nvram, diff, ctlrl, etc.) into either a subfolder within the libretro 'save' folder or within the libretro 'system' folder depending on the content.

These subfolders are created if they do not already exist.

Edit:

This is intended to resolve issues:

* https://github.com/libretro/mame2010-libretro/issues/14
* https://github.com/libretro/mame2010-libretro/issues/38
* https://github.com/libretro/mame2010-libretro/issues/31
* https://github.com/libretro/mame2010-libretro/issues/15
* https://github.com/libretro/mame2010-libretro/issues/11

### CODE REVIEW

**Comment by r-type** [comment]
yes , path_mkdir(path) will take care of this .
else you have to deal with 

#if defined(_WIN32)
      int ret = _mkdir(dir);
#elif defined(IOS)
      int ret = mkdir(dir, 0755);
#elif defined(VITA) || defined(PSP)
      int ret = sceIoMkdir(dir, 0777);
#elif defined(__QNX__)
      int ret = mkdir(dir, 0777);
#else
      int ret = mkdir(dir, 0750);
#endif

**Comment by markwkidd** [comment]
I'm compiling a patched version that uses path_mkdir(path) to make sure my
edits are clean. https://github.com/markwkidd/mame2010-libretro/tree/patch-4

Assuming it compiles cleanly I'll create a PR and post here again.

**Comment by r-type** [comment]
hum ... i think you will need more than file_path.h
you can look here to see how i done it for mame2000.

https://github.com/libretro/mame2000-libretro/commit/8a65a0336cca9891ad8fd9ff02a99c41def2f046

**Comment by markwkidd** [comment]
@r-type you are right -- I need to bring in several new files from libretro-common

I think I may have every file I need now in my branch at https://github.com/markwkidd/mame2010-libretro/tree/patch-4

What is stopping me is I'm having a hard time figuring out how to add `file_path.c` to `Makefile.common`. mame2010 uses a more complex structure, and I am not sure where to 'plug in' new `.c` sources as in your mame2000 example. Could you give me any more advice on the Makefile?

**Comment by r-type** [comment]
i bet i will try to  add it here
https://github.com/libretro/mame2010-libretro/blob/master/Makefile.common#L4553

OSDOBJS += $(OBJ)/osd/retro/retromain.o  $(OBJ)/osd/retro/libretro-common/file/file_path.o

**Comment by markwkidd** [comment]
Thank you -- that was the right suggestion.

Frustratingly, I am still trying to deal with a few compilation errors like `conflicting specifiers in declaration` from the new libretro-common source files.

I am close to getting this code switched over to path_mkdir but I need to take a break from this for a few hours. I apologize for stepping away while this is still not building for everyone. I will continue work ASAP.

**Comment by markwkidd** [comment]
I just submitted a PR to comment out only the mkdir statements for now: https://github.com/libretro/mame2010-libretro/pull/88

Before my patches, there was no directory creation so it seems ok to comment them out until I can implement the libretro-common solution

**Pull request merged**
