### PR TITLE
make console logging a bit more verbose

### PR DESCRIPTION
**Pull request by markwkidd**
Help users figure out where these folders are on their local machine without enabling verbose log.

### CODE REVIEW

**Comment by twinaphex** [comment]
Why are you using printf instead of log_cb ? I see you replacing log_cb calls with printf/fprintf calls - that is not what we should do.

**Comment by markwkidd** [comment]
How can we log something to the screen without using verbose? I'll look
once I get back to home base.

**Comment by twinaphex** [comment]
OK so you want these messages to be printed on screen instead of console logging?

You need a different function for that - there are some cores that do this like pcsx rearmed, where it prints a message with the OSD onscreen text.

**Comment by markwkidd** [comment]
Thank you for giving me the starting point. I'll submit a new and improved
PR once I'm up to speed.

**Pull request closed without merging**
