### PR TITLE
Fix for Issues #129 and #130

### PR DESCRIPTION
**Pull request by c0d3h4x0r**
Fix for https://github.com/libretro/mame2010-libretro/issues/130

### CODE REVIEW

**Comment by c0d3h4x0r** [comment]
This also fixes the similar "illegal instruction" crash while trying to launch "Golden Axe: The Duel".

**Comment by paradadf** [comment]
There are other platforms supported by retropie, not only rpi. Imo you should try to find a more generic way for the platform identification.

**Comment by c0d3h4x0r** [comment]
I looked for a more generic way and couldn’t find one.  This change is better and no worse than what’s in the code already, so I’d recommend taking it.

(sent from my mobile phone)

On Jul 10, 2019, at 4:55 AM, paradadf <notifications@github.com<mailto:notifications@github.com>> wrote:


There are other platforms supported by retropie, not only rpi. Imo you should try to find a more generic way for the platform identification.

**Comment by dankcushions** [comment]
shouldn't `platform` be fed in by the make command? eg in mame2003
https://github.com/libretro/mame2003-libretro/blob/master/Makefile#L155

retropie will set `platform` when building via it's internal scripts. i suggest just copying the fallbacks from https://github.com/libretro/mame2003-libretro/blob/master/Makefile#L32 and assume the builder will feed in anything special.

**Comment by c0d3h4x0r** [comment]
Maybe there’s a bug in RetroPie-Setup.  I’ll look into it.

(sent from my mobile phone)

On Jul 10, 2019, at 9:12 AM, dankcushions <notifications@github.com<mailto:notifications@github.com>> wrote:


shouldn't platform be fed in by the make command? eg in mame2003
https://github.com/libretro/mame2003-libretro/blob/master/Makefile#L155<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Flibretro%2Fmame2003-libretro%2Fblob%2Fmaster%2FMakefile%23L155&data=02%7C01%7C%7C4949c96a0eaa4c54b4d608d70551687a%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636983719507718578&sdata=ZAKNpmnlNprjP03An%2B7%2FMK0dz9H484A8VTYSxwC4iUI%3D&reserved=0>

retropie will set platform when building via it's internal scripts. i suggest just copying the fallbacks from https://github.com/libretro/mame2003-libretro/blob/master/Makefile#L32<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Flibretro%2Fmame2003-libretro%2Fblob%2Fmaster%2FMakefile%23L32&data=02%7C01%7C%7C4949c96a0eaa4c54b4d608d70551687a%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636983719507728589&sdata=kb3GpkiPAKWpGZPRUexrbO2oUeYUi1qBKJ9ekRy8haM%3D&reserved=0> and assume the builder will feed in anything special.

**Comment by c0d3h4x0r** [comment]
Yeah, looks like an oversight in `RetroPie-Setup/scriptmodules/libretrocores/lr-mame2010.sh`.  I'm preparing a separate fix for that, and I'll update this pull request accordingly.

**Pull request merged**
